---
- name: Despliega los detalles del rol.
  debug:
    msg:
      - '===================================================================='
      - 'runit.odoo'
      - 'Colección para desplegar Odoo..'
      - '===================================================================='