---
- name: Converge
  hosts: all
  gather_facts: true
  vars_files:
    - ../../defaults/main.yml

  pre_tasks:
    - name: '[Pre] Actualiza el caché APT.'
      apt: update_cache=yes cache_valid_time=3600
      when: not ansible_check_mode

  roles:
    - coopdevs.odoo-role
    - name: odoo
